// Migration pallets in order (updated for Kusama)
export const MIGRATION_PALLETS = [
  'PureProxyCandidates',
  'Accounts',
  'Multisig',
  'Claims',
  'Proxy',
  'Preimage',
  'NomPools',
  'Vesting',
  'DelegatedStaking',
  'Indices',
  'Referenda',
  'BagsList',
  'Scheduler',
  'ConvictionVoting',
  'Bounties',
  'ChildBounties',
  'AssetRate',
  'Crowdloan',
  'Treasury',
  'Recovery',
  'Society',
  'Staking'
]; 